version: 2.1

orbs:
  ruby: circleci/ruby@1.1.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.2.22

  test:
    docker:
      - image: circleci/postgres:13.0
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: blog_rails6_test
          POSTGRES_HOST_AUTH_METHOD: trust # パスワードなし
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: circleci
      PGPASSWORD: ""
      TZ: "/usr/share/zoneinfo/Asia/Tokyo"
      RAILS_ENV: test

    steps:
      - checkout
      - ruby/install-deps:
          bundler-version: 2.2.22
      - run:
          name: DB Initializing
          command: |
            dockerize -wait tcp://localhost:5432 -timeout 1m
            bundle exec rake db:schema:load
      - run:
          name: test
          command: |
            rails test
      - store_test_results:
          path: test_results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
